#!/bin/bash

# 🚀 PRÓXIMOS PASSOS - PUSH PARA GITHUB/GITLAB
#
# Este arquivo documenta como fazer o push inicial do projeto

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                        ║"
echo "║       🚀 FAZER PUSH PARA GITHUB / GITLAB - INSTRUÇÕES 🚀             ║"
echo "║                                                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

echo "Estado atual:"
echo ""
echo "✅ Git Flow configurado localmente"
echo "✅ Branches: main, develop, feature/gitflow-setup"
echo "✅ 3 commits feitos:"
echo "   1. ef9e6b9 🚀 Bootcamp 2026 - Setup Inicial"
echo "   2. 594f66d 🌳 Feature: Setup Git Flow"
echo "   3. c01a07c 📊 Docs: Resumo de status"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "📋 PASSO 1: CRIAR REPOSITÓRIO NO GITHUB OU GITLAB"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "OPÇÃO A - GITHUB (recomendado para trabalho individual)"
echo "───────────────────────────────────────────────────────"
echo ""
echo "1. Ir para: https://github.com/new"
echo "2. Preencher:"
echo "   - Repository name: bootcamp-2026"
echo "   - Description: Adobe AEM + Commerce + Shopify Bootcamp Integration"
echo "   - Selecionar: Public (ou Private, sua escolha)"
echo "   - NÃO selecionar: Initialize with README (já temos)"
echo "3. Clicar: Create Repository"
echo ""

echo "OPÇÃO B - GITLAB (bom para equipes)"
echo "────────────────────────────────────"
echo ""
echo "1. Ir para: https://gitlab.com/projects/new"
echo "2. Preencher:"
echo "   - Project name: bootcamp-2026"
echo "   - Project slug: bootcamp-2026"
echo "   - Description: Adobe AEM + Commerce + Shopify Bootcamp"
echo "   - Visibility: Public (ou Private)"
echo "3. Clicar: Create project"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🔐 PASSO 2: CONFIGURAR AUTENTICAÇÃO SSH (recomendado)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Ter SSH configurado evita precisar digitar senha toda vez"
echo ""
echo "# Verificar se já tem SSH"
echo "ls ~/.ssh/id_rsa"
echo ""
echo "# Se não tiver, criar:"
echo "ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N \"\""
echo ""
echo "# Copiar chave pública:"
echo "cat ~/.ssh/id_rsa.pub"
echo ""
echo "# Ir para GitHub/GitLab:"
echo "  GitHub: Settings → SSH and GPG keys → New SSH key"
echo "  GitLab: Edit profile → SSH Keys"
echo ""
echo "# Colar e salvar"
echo ""
echo "# Testar:"
echo "ssh -T git@github.com    # GitHub"
echo "ssh -T git@gitlab.com    # GitLab"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🌳 PASSO 3: CONFIGURAR REMOTO E FAZER PUSH"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "OPÇÃO A - Via SSH (depois de configurar SSH acima)"
echo "───────────────────────────────────────────────"
echo ""
echo "# GitHub:"
echo "cd /home/igors/projects/bootcamp-2026"
echo "git remote add origin git@github.com:SEU-USERNAME/bootcamp-2026.git"
echo "git branch -M main"
echo "git push -u origin main"
echo "git push -u origin develop"
echo "git push -u origin feature/gitflow-setup"
echo ""

echo "# GitLab:"
echo "cd /home/igors/projects/bootcamp-2026"
echo "git remote add origin git@gitlab.com:SEU-USERNAME/bootcamp-2026.git"
echo "git branch -M main"
echo "git push -u origin main"
echo "git push -u origin develop"
echo "git push -u origin feature/gitflow-setup"
echo ""

echo "OPÇÃO B - Via HTTPS (sem SSH, mas precisa digitar senha)"
echo "──────────────────────────────────────────────────────"
echo ""
echo "# GitHub:"
echo "cd /home/igors/projects/bootcamp-2026"
echo "git remote add origin https://github.com/SEU-USERNAME/bootcamp-2026.git"
echo "git branch -M main"
echo "git push -u origin main"
echo "git push -u origin develop"
echo "git push -u origin feature/gitflow-setup"
echo ""

echo "# GitLab:"
echo "cd /home/igors/projects/bootcamp-2026"
echo "git remote add origin https://gitlab.com/SEU-USERNAME/bootcamp-2026.git"
echo "git branch -M main"
echo "git push -u origin main"
echo "git push -u origin develop"
echo "git push -u origin feature/gitflow-setup"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🔄 PASSO 4: CRIAR PULL REQUEST (FEATURE → DEVELOP)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Depois que fazer push, criar PR:"
echo ""
echo "GITHUB:"
echo "1. Ir para seu repositório no GitHub"
echo "2. Você verá banner: 'feature/gitflow-setup had recent pushes'"
echo "3. Clicar: 'Compare & pull request'"
echo "4. Base: develop | Compare: feature/gitflow-setup"
echo "5. Título: '🌳 Setup: Configurar Git Flow com branches'"
echo "6. Descrição:"
echo "   Configuração inicial do Git Flow com:"
echo "   - Branch develop criado"
echo "   - Template de commit"
echo "   - Pre-commit hooks"
echo "   - Documentação completa"
echo "7. Clicar: 'Create pull request'"
echo "8. Revisar mudanças"
echo "9. Clicar: 'Merge pull request'"
echo ""

echo "GITLAB:"
echo "1. Ir para seu repositório no GitLab"
echo "2. Você verá notificação de push recente"
echo "3. Clicar em 'Create merge request'"
echo "4. Source branch: feature/gitflow-setup | Target branch: develop"
echo "5. Preencher título e descrição"
echo "6. Clicar: 'Create merge request'"
echo "7. Clicar: 'Merge'"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "✅ PASSO 5: ATUALIZAR LOCAL COM MUDANÇAS"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Depois de fazer merge no remoto:"
echo ""
echo "# Trazer mudanças develop"
echo "git checkout develop"
echo "git pull"
echo ""
echo "# Limpar feature branch local"
echo "git branch -d feature/gitflow-setup"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "🎯 PASSO 6: COMEÇAR PRÓXIMA FEATURE (FASE 1)"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "Agora pronto para começar Phase 1:"
echo ""
echo "git checkout -b feature/fase-1-magento-setup"
echo ""
echo "E seguir SETUP.md para:"
echo "- Criar atributos em Magento"
echo "- Criar categorias"
echo "- Criar produtos"
echo "- Ativar módulo CatalogApi"
echo "- Testar API endpoint"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "📚 REFERÊNCIA RÁPIDA"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

cat << 'TABLE'
COMANDO                              | O QUE FAZ
─────────────────────────────────────┼───────────────────────────────────
git remote add origin URL             | Conectar ao repositório remoto
git branch -M main                    | Renomear master → main
git push -u origin main               | Enviar branch main
git push -u origin develop            | Enviar branch develop
git status                            | Ver status atual
git branch -a                         | Ver todos os branches
git log --oneline                     | Ver histórico de commits
TABLE

echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "⚠️  ERROS COMUNS E SOLUÇÕES"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "❌ Erro: fatal: 'origin' does not exist"
echo "✅ Solução: Executar 'git remote add origin URL'"
echo ""

echo "❌ Erro: Permission denied (publickey)"
echo "✅ Solução: Configurar SSH (PASSO 2 acima)"
echo ""

echo "❌ Erro: Please make sure you have the correct access rights"
echo "✅ Solução: Verificar SSH ou usar HTTPS com token"
echo ""

echo "❌ Erro: fatal: refspec main does not match any"
echo "✅ Solução: master → main: git branch -M main"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 PRÓXIMAS AÇÕES:"
echo ""
echo "1️⃣ Escolher GitHub ou GitLab e criar repositório"
echo "2️⃣ Configurar SSH (opcional mas recomendado)"
echo "3️⃣ Executar comandos git remote add / git push"
echo "4️⃣ Criar Pull Request no GitHub/GitLab"
echo "5️⃣ Fazer merge para develop"
echo "6️⃣ Começar feature/fase-1-magento-setup"
echo ""
echo "════════════════════════════════════════════════════════════════════════"

