#!/bin/bash
# 🚀 Bootcamp 2026 - Comandos Essenciais para Começar

echo "╔═════════════════════════════════════════════════════════════════════╗"
echo "║                 🎉 BOOTCAMP 2026 - LET'S GO! 🎉                    ║"
echo "║            Integração Adobe Commerce + AEM + Shopify Hydrogen      ║"
echo "╚═════════════════════════════════════════════════════════════════════╝"
echo ""

# Cores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📁 Projeto localizado em:${NC}"
echo "   /home/igors/projects/bootcamp-2026"
echo ""

echo -e "${BLUE}📊 Estrutura do Projeto:${NC}"
echo "   26 arquivos criados"
echo "   4.482+ linhas de código"
echo "   6 fases de desenvolvimento"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}📖 PASSO 1: LER DOCUMENTAÇÃO (30 minutos)${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "1️⃣  Visão Geral (5 min):"
echo "   cd /home/igors/projects/bootcamp-2026"
echo "   cat README.md"
echo ""
echo "2️⃣  Índice Visual (5 min):"
echo "   cat INDEX.md"
echo ""
echo "3️⃣  Início Rápido (10 min):"
echo "   cat QUICK-START.md"
echo ""
echo "4️⃣  Resumo Executivo (10 min):"
echo "   cat RESUMO-EXECUTIVO.md"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}🚀 PASSO 2: PREPARAR AMBIENTE (10 minutos)${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "1️⃣  Verificar se Magento está rodando:"
echo "   curl -s https://app.magento2.test/admin 2>&1 | head -5"
echo ""
echo "2️⃣  Verificar se AEM está rodando:"
echo "   curl -s http://localhost:4502 2>&1 | head -5"
echo ""
echo "3️⃣  Estrutura está pronta:"
echo "   ls -la /home/igors/projects/bootcamp-2026/"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}✅ PASSO 3: COMEÇAR DESENVOLVIMENTO (40-60 horas)${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Abrir SETUP.md completo para guia passo a passo:"
echo "   cat SETUP.md | less"
echo ""
echo "Ou abra em editor:"
echo "   code /home/igors/projects/bootcamp-2026/SETUP.md"
echo ""
echo "Fases:"
echo "   ✓ Fase 1 (Dias 11-14): Adobe Commerce"
echo "   ✓ Fase 2 (Dia 12):     AEM Content Fragments"
echo "   ✓ Fase 3 (Dia 15):     Integração AEM + Commerce"
echo "   ✓ Fase 4 (Dia 13):     Shopify Liquid & Metafields"
echo "   ✓ Fase 5 (Dia 16):     Shopify Hydrogen"
echo "   ✓ Fase 6 (Dia 17):     Integração Final"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}🧪 PASSO 4: TESTAR E VALIDAR (Contínuo)${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Exemplos de API (copiar e colar):"
echo "   cat docs/endpoints.md | grep 'curl' | head -5"
echo ""
echo "Ou abra o arquivo completo:"
echo "   code /home/igors/projects/bootcamp-2026/docs/endpoints.md"
echo ""
echo "Rastrear progresso:"
echo "   cat docs/checklist.md | head -50"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}📚 ARQUIVOS DE REFERÊNCIA RÁPIDA${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}✅ README.md${NC}"
echo "   • Visão geral do projeto"
echo "   • Arquitetura (diagrama ASCII)"
echo "   • URLs de acesso"
echo "   • Troubleshooting"
echo ""
echo -e "${GREEN}✅ QUICK-START.md${NC}"
echo "   • Resumo rápido"
echo "   • Ordem de fases"
echo "   • Verificação rápida"
echo ""
echo -e "${GREEN}✅ SETUP.md${NC}"
echo "   • Guia completo passo a passo"
echo "   • Comandos prontos para copiar"
echo "   • Instruções detalhadas"
echo ""
echo -e "${GREEN}✅ docs/checklist.md${NC}"
echo "   • 100+ itens verificáveis"
echo "   • Um para cada dia"
echo "   • Validação final"
echo ""
echo -e "${GREEN}✅ docs/endpoints.md${NC}"
echo "   • APIs completas"
echo "   • Autenticação"
echo "   • Exemplos de cURL"
echo "   • Responses esperadas"
echo ""
echo -e "${GREEN}✅ docs/arquitetura.md${NC}"
echo "   • Diagramas de fluxos"
echo "   • Timings"
echo "   • Fallbacks"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}🎯 COMECE AGORA${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Escolha uma opção:"
echo ""
echo "  A) Ver documentação no VS Code:"
echo "     code /home/igors/projects/bootcamp-2026"
echo ""
echo "  B) Começar a ler README:"
echo "     cat /home/igors/projects/bootcamp-2026/README.md | less"
echo ""
echo "  C) Ir direto para SETUP:"
echo "     cat /home/igors/projects/bootcamp-2026/SETUP.md | less"
echo ""
echo "  D) Ver estrutura do projeto:"
echo "     cd /home/igors/projects/bootcamp-2026 && tree"
echo ""
echo "  E) Listar todos os arquivos:"
echo "     find /home/igors/projects/bootcamp-2026 -type f | sort"
echo ""

echo -e "${YELLOW}═════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}✨ Tudo pronto! Boa sorte no Bootcamp 2026! ✨${NC}"
echo ""
echo "Qualquer dúvida, consulte os arquivos de documentação."
echo ""
echo "═════════════════════════════════════════════════════════════════════"
